import type { Metadata } from "next";
import {
  ClerkProvider,
  ClerkLoaded, ClerkLoading
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// ✅ Load fonts correctly
const geistSans = Geist({
  subsets: ["latin"],
  display: "swap", // ✅ Prevents layout shift
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});

// ✅ Metadata configuration
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      
      {/* ✅ Add suppressHydrationWarning to prevent hydration mismatches */}
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
        suppressHydrationWarning
      >
        <header style={{ display: 'flex', justifyContent:'center', alignItems:'center',}}>
          <Navbar/>
          </header>
          <ClerkLoading>
            <div>Starting Examina-AI.... </div>
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
      </body>
    </html>
    </ClerkProvider>
  );
}
